### ISSUE TITLE
SFW IDs: `serious-kids-suffer`

### ISSUE THREAD

**Issue by Skn0tt** [RienNeVaPlus/human-id#8]
Hey there! Good work with this library, really enjoy seeing those human-readable IDs generated by `changeset` (which uses this internally).

In your README, you mention that the IDs generated by this library are safe for work. I like that! Today, I came across the ID `serious-kids-suffer`, which felt very moody to me. It's certainly safe for work, but I wouldn't exactly call it "family friendly". I get that this library is essentially doing random combinations of words. I'm unsure if `suffer` is a good verb to use, though, since it has the potential of making pretty dark IDs. Would it make sense  to replace it with something more chipper?

**Comment by RienNeVaPlus** [comment]
Thanks for reporting this. `suffer` has been replaced with `strive`.

**Comment by Skn0tt** [comment]
Thanks for the super-quick turnaround! Much appreciated :)
